#!/usr/bin/bash
#It has been configured to be used in herbstluftwm
#############################################################################################################################
############################################################################################################################# 
###                                                                                                                       ###
###                                                     Dzen2 Bar                                                         ### 
###                                                                                                                       ###
#############################################################################################################################
############################################################################################################################# 


## Dzen Config
##############
##############
monitor=${1:-0}
geometry=( $(herbstclient monitor_rect "$monitor") )

ICON_PATH="$HOME/.dzen2/icon"
BLACK='#000000'
BLACK2='#151515'
RED='#770000'
GRAY='#BEBEBE'
GRAY2='#222222'
WHITE='#FFFFFF'
PINK='#FF00FF'
BLUE='#0066CC'
YELLOW='#d6d600'

FONT="-*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*"
X=${geometry[0]} 
Y=${geometry[1]}
WIDTH=${geometry[2]} 
HEIGHT=16
 
herbstclient pad $monitor $HEIGHT

## Dzen2 Info
#############
#############
Tag()
{
    TAGS=( $(herbstclient tag_status $monitor) )
    for i in "${TAGS[@]}"
    do
        case ${i:0:1} in
            '#')
                echo -n "^bg($BLACK)^fg($YELLOW)"
                ;;
            '+')
                echo -n "^bg(#9CA668)^fg(#141414)"
                ;;
            ':')
                echo -n "^bg($BLACK)^fg($WHITE)"
                ;;
            '!')
                echo -n "^bg(#FF0675)^fg(#141414)"
                ;;
             *)
                echo -n "^bg()^fg()"
                ;;
        esac
  
        echo -n "^ca(1,\"${herbstclient_command[@]:-herbstclient}\" "
        echo -n "focus_monitor \"$monitor\" && "
        echo -n "\"${herbstclient_command[@]:-herbstclient}\" "              
        echo -n "use \"${i:1}\") ${i:1} ^ca()"
    done
}
    
Kernel()
{
    kernel=$(uname -r | grep -Eo '([0-9]*)\.([0-9]*)\.([0-9]*)\-([0-9]*)')
    echo -n "^i($ICON_PATH/arch.xbm) $kernel"
}

Cpu()
{
    cpu=$(cpupower frequency-info -fm | awk '{print $4$5}' | sed '1d')
    #cpu_percent=$(cpupower frequency-info -f | awk '{print $4/1700000*100}' | grep -Eo '[0-9]+\.[0-9].')
    echo -n "^i($ICON_PATH/cpu.xbm) $cpu"                                             
}

Root()
{
    root_free=$(df -h / | sed '1d' | awk '{print $4}')
    #root_free_percent=$(df -h /home | sed '1d' | awk '{print $5}')
    echo -n "^i($ICON_PATH/root.xbm) $root_free" 
}

Home()
{
    home_free=$(df -h /home | sed '1d' | awk '{print $4}')
    #home_free_percent=$(df -h /home | sed '1d' | awk '{print $5}')
    echo -n "^i($ICON_PATH/hd.xbm) $home_free" 
}

Ram()
{
    ram=$(free -mh | awk '{print $3}' | sed '1d' | sed '2d')
    ram_percent=$(free | grep Mem | awk '{print $3/$2 * 100}' | grep -Eo '([0-9]*)\.([0-9].)')
    echo -n "^i($ICON_PATH/ram.xbm) $ram $ram_percent%"
}

Swap()
{
    swap=$(free -mh | awk '{print $3}' | sed '1d' | sed '1d')
    #swap_percent=$(free | grep Swap | awk '{print $3/$2 * 100}' | grep -Eo '([0-9]*)')
    echo -n "^i($ICON_PATH/swap.xbm) $swap" #$swap_percent% "
}

Temp()
{
    temp=$(sensors | grep Package | awk '{print $4}'| grep -Eo '([0-9]+)\.([0-9]+)')
    echo -n "^i($ICON_PATH/temp.xbm) $temp°C" 
}     

Battery()
{
    battery=$(acpi -b | grep -Po "\d{1,}%")
    batterystatus=$(acpi -b | grep -Eo "(Charging|Full)")
    timeofcharging=$(acpi -b | awk '{print $5}' | grep -Eo '([0-9]+:([0-9]+))')

    case $batterystatus in 
        "Full") echo -n "^i($ICON_PATH/battery.xbm) $battery" ;;
        "Charging") echo -n "^i($ICON_PATH/charging.xbm) $battery $timeofcharging" ;;
        *) echo -n "^i($ICON_PATH/discharging.xbm) $battery $timeofcharging" ;; 
    esac
}

Brightness()
{
    brightness=$(xbacklight -get | grep -Eo '([0-9]*)\.([0-9].)')
    echo -n "^i($ICON_PATH/brightness.xbm) $brightness%"
}     

Wifi()
{
    #wifi_percent=$(nmcli dev wifi | grep $(nmcli dev | awk '{print $4}' | sed '3,4d' | sed '1d') | awk '{print $7}')
    case $wifi_name in
        "BlackMamba") echo -n "^i($ICON_PATH/wifi.xbm) $wifi_name" ;;
        *) echo -n "Not Connected" ;;
    esac
}

Date()
{
    date=$(date +%d).$(date +%b)
    echo -n "^i($ICON_PATH/calendar.xbm) $date"
}

Time()
{
    hour=$(date +%H:%M)
    echo -n "^i($ICON_PATH/clock.xbm) $hour"
}

## Print Dzen2
##############
##############
# change bar size depending on wifi name
wifi_name=$(nmcli dev | awk '{print $4}' | sed '3,4d' | sed '1d')
case $wifi_name in 
    "BlackMamba") pa=912 ;;
    *) pa=880 ;;
esac
    
while true                                                                                                                       
do
    echo "^fg($BLACK)^bg($GRAY2)^pa(0) $(Kernel) $(Cpu) $(Root) $(Home) $(Ram) $(Swap)^fg()^bg()^fg($GRAY2)^i($ICON_PATH/rightarrow.xbm)^i($ICON_PATH/rightarrow2.xbm)^fg() \
^pa(615)$(Tag) ^pa($pa)^fg($GRAY2)^i($ICON_PATH/leftarrow2.xbm)^i($ICON_PATH/leftarrow.xbm)^fg()^bg($GRAY2)^fg($BLACK)$(Temp) $(Battery) $(Brightness) $(Wifi) $(Date) $(Time)^fg() "
    sleep 1
done | dzen2 -ta l -fn $FONT -bg $BLACK -fg $GRAY -x $X -y $Y -w $WIDTH -h $HEIGHT
