#!/usr/bin/bash
#############################################################################################################################
############################################################################################################################# 
###                                                                                                                       ###
###                                                     Dzen2 Bar                                                         ### 
###                                                                                                                       ###
#############################################################################################################################
############################################################################################################################# 


## Dzen Config
##############
##############
ICON_PATH="$HOME/.dzen2/icon"
BLACK='#000000'
BLACK2='#151515'
RED='#770000'
GRAY='#BEBEBE'
GRAY2='#222222'
WHITE='#FFFFFF'
PINK='#FF00FF'
BLUE='#0066CC'

FONT="-*-terminus-medium-r-*-*-13-*-*-*-*-*-iso10646-*"
WIDTH=800
X=565
W=800

#SEPARATOR="^bg(#000000)^fg($DZEN_BLACK)^i($ICON_PATH/r_arr.xbm)^fg()^bg()^bg($RED) "
#SEPARATOR2="^bg($RED)^fg(#000000)^i($ICON_PATH/r_arr.xbm)^fg()^bg()^bg(#000000) "

## Dzen2 Info
#############
#############
Kernel()
{
    kernel=$(uname -r | grep -Eo '([0-9]*)\.([0-9]*)\.([0-9]*)\-([0-9]*)')
    echo -n "^fg($RED)^i($ICON_PATH/arch.xbm)^fg() $kernel"
    return
}

Cpu()
{
    cpu=$(cpupower frequency-info -fm | awk '{print $4$5}' | sed '1d')
    #cpu_percent=$(cpupower frequency-info -f | awk '{print $4/1700000*100}' | grep -Eo '[0-9]+\.[0-9].')
    echo -n "^fg($RED)^i($ICON_PATH/cpu.xbm)^fg() $cpu"                                             
    return
}

Root()
{
    root_free=$(df -h / | sed '1d' | awk '{print $4}')
    #root_free_percent=$(df -h /home | sed '1d' | awk '{print $5}')
    echo -n "^fg($RED)^i($ICON_PATH/root.xbm)^fg() $root_free" 
    return
}

Home()
{
    home_free=$(df -h /home | sed '1d' | awk '{print $4}')
    #home_free_percent=$(df -h /home | sed '1d' | awk '{print $5}')
    echo -n "^fg($RED)^i($ICON_PATH/hd.xbm)^fg() $home_free" 
    return
}

Ram()
{
    ram=$(free -mh | awk '{print $3}' | sed '1d' | sed '2d')
    ram_percent=$(free | grep Mem | awk '{print $3/$2 * 100}' | grep -Eo '([0-9]*)\.([0-9].)')
    echo -n "^fg($RED)^i($ICON_PATH/ram.xbm)^fg() $ram $ram_percent%"
    return
}

Swap()
{
    swap=$(free -mh | awk '{print $3}' | sed '1d' | sed '1d')
    #swap_percent=$(free | grep Swap | awk '{print $3/$2 * 100}' | grep -Eo '([0-9]*)')
    echo -n "^fg($RED)^i($ICON_PATH/swap.xbm)^fg() $swap" #$swap_percent% "
    return
}

Temp()
{
    temp=$(sensors | grep Package | awk '{print $4}'| grep -Eo '([0-9]+)\.([0-9]+)')
    echo -n "^fg($RED)^i($ICON_PATH/temp.xbm)^fg() $temp°C" 
    return
}     

Battery()
{
    battery=$(acpi -b | grep -Po "\d{1,}%")
    charging=$(acpi -b | grep -Eo "(arging|Full)")
    timeofcharging=$(acpi -b | awk '{print $5}' | grep -Eo '([0-9]+:([0-9]+))')

    if test $charging == "Full"
    then 
	    echo -n "^fg($RED)^i($ICON_PATH/battery.xbm)^fg() $battery"
    else
	    echo -n "^fg($RED)^i($ICON_PATH/charging.xbm)^fg() $battery $timeofcharging" 
    fi
    return
}

Brightness()
{
    brightness=$(xbacklight -get | grep -Eo '([0-9]*)\.([0-9].)')
    echo -n "^fg($RED)^i($ICON_PATH/brightness.xbm)^fg() $brightness%"
    return
}     

Wifi()
{
    wifi_name=$(nmcli dev | awk '{print $4}' | sed '3,4d' | sed '1d')
    if test -n $wifi_name
    then
        echo -n "^fg($RED)^i($ICON_PATH/wifi.xbm)^fg() $wifi_name"
    else
        echo -n "Not Connected "
    fi
    return
}

Date()
{
    date="$(date +"%d").$(date +"%b")"
    echo -n "^fg($RED)^i($ICON_PATH/calendar.xbm)^fg() $date"
    return
}

Time()
{
    hour=$(date +"%H:%M")
    echo -n "^fg($RED)^i($ICON_PATH/clock.xbm)^fg() $hour"
    return
}

## Print Dzen2
##############
##############
while true
do
    echo "$(Kernel) $(Cpu) $(Root) $(Home) $(Ram) $(Swap) $(Temp) $(Battery) $(Brightness) $(Wifi) $(Date) $(Time)"
    sleep 0.1
done | dzen2 -ta l -fn $FONT -bg $BLACK -fg $GRAY -x $X -w $W
