#!/usr/bin/bash
#It has been configured to be used in herbstluftwm
#############################################################################################################################
############################################################################################################################# 
###                                                                                                                       ###
###                                                     Dzen2 Bar                                                         ### 
###                                                                                                                       ###
#############################################################################################################################
############################################################################################################################# 


## Dzen Config
##############
##############
monitor=${1:-0}
geometry=( $(herbstclient monitor_rect "$monitor") )

ICON_PATH="$HOME/.dzen2/icon"
BLACK='#000000'
BLACK2='#151515'
RED='#770000'
GRAY='#BEBEBE'
GRAY2='#222222'
WHITE='#FFFFFF'
PINK='#FF00FF'
BLUE='#0066CC'

FONT="-*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*"
X=${geometry[0]} 
Y=${geometry[1]}
WIDTH=${geometry[2]} 
HEIGHT=16
 
herbstclient pad $monitor $HEIGHT

## Dzen2 Info
#############
#############
function Tag
{
    TAGS=( $(herbstclient tag_status $monitor) )
    for i in "${TAGS[@]}"
    do
        case ${i:0:1} in
            '#')
                echo -n "^bg($BLACK2)^fg($PINK)"
                ;;
            '+')
                echo -n "^bg(#9CA668)^fg(#141414)"
                ;;
            ':')
                echo -n "^bg($BLACK2)^fg($BLUE)"
                ;;
            '!')
                echo -n "^bg(#FF0675)^fg(#141414)"
                ;;
             *)
                echo -n "^bg()^fg()"
                ;;
        esac
  
        echo -n "^ca(1,\"${herbstclient_command[@]:-herbstclient}\" "
        echo -n "focus_monitor \"$monitor\" && "
        echo -n "\"${herbstclient_command[@]:-herbstclient}\" "              
        echo -n "use \"${i:1}\") ${i:1} ^ca()"
    done
    return
}
    
function Kernel()
{
    kernel=$(uname -r | grep -Eo '([0-9]*)\.([0-9]*)\.([0-9]*)\-([0-9]*)')
    echo -n "^fg($BLUE)^i($ICON_PATH/arch.xbm)^fg() $kernel"
    return
}

function Cpu()
{
    cpu=$(cpupower frequency-info -fm | awk '{print $4$5}' | sed '1d')
    #cpu_percent=$(cpupower frequency-info -f | awk '{print $4/1700000*100}' | grep -Eo '[0-9]+\.[0-9].')
    echo -n "^fg($BLUE)^i($ICON_PATH/cpu.xbm)^fg() $cpu"                                             
    return
}

function Root()
{
    root_free=$(df -h / | sed '1d' | awk '{print $4}')
    #root_free_percent=$(df -h /home | sed '1d' | awk '{print $5}')
    echo -n "^fg($BLUE)^i($ICON_PATH/root.xbm)^fg() $root_free" 
    return
}

function Home()
{
    home_free=$(df -h /home | sed '1d' | awk '{print $4}')
    #home_free_percent=$(df -h /home | sed '1d' | awk '{print $5}')
    echo -n "^fg($BLUE)^i($ICON_PATH/hd.xbm)^fg() $home_free" 
    return
}

function Ram()
{
    ram=$(free -mh | awk '{print $3}' | sed '1d' | sed '2d')
    ram_percent=$(free | grep Mem | awk '{print $3/$2 * 100}' | grep -Eo '([0-9]*)\.([0-9].)')
    echo -n "^fg($BLUE)^i($ICON_PATH/ram.xbm)^fg() $ram $ram_percent%"
    return
}

function Swap()
{
    swap=$(free -mh | awk '{print $3}' | sed '1d' | sed '1d')
    #swap_percent=$(free | grep Swap | awk '{print $3/$2 * 100}' | grep -Eo '([0-9]*)')
    echo -n "^fg($BLUE)^i($ICON_PATH/swap.xbm)^fg() $swap" #$swap_percent% "
    return
}

function Temp()
{
    temp=$(sensors | grep Package | awk '{print $4}'| grep -Eo '([0-9]+)\.([0-9]+)')
    echo -n "^fg($PINK)^i($ICON_PATH/temp.xbm)^fg() $temp°C" 
    return
}     

function Battery
{
    battery=$(acpi -b | grep -Po "\d{1,}%")
    batterystatus=$(acpi -b | grep -Eo "(Charging|Full)")
    timeofcharging=$(acpi -b | awk '{print $5}' | grep -Eo '([0-9]+:([0-9]+))')

    if test $batterystatus == "Full"
    then 
	    echo -n "^fg($PINK)^i($ICON_PATH/battery.xbm)^fg() $battery"
    elif test $batterystatus == "Charging"
    then
        echo -n "^fg($PINK)^i($ICON_PATH/charging.xbm)^fg() $battery $timeofcharging"
    else
	    echo -n "^fg($PINK)^i($ICON_PATH/discharging.xbm)^fg() $battery $timeofcharging" 
    fi
    return
}

function Brightness()
{
    brightness=$(xbacklight -get | grep -Eo '([0-9]*)\.([0-9].)')
    echo -n "^fg($PINK)^i($ICON_PATH/brightness.xbm)^fg() $brightness%"
    return
}     

function Wifi()
{
    wifi_name=$(nmcli dev | awk '{print $4}' | sed '3,4d' | sed '1d')
    if test -n $wifi_name
    then
        echo -n "^fg($PINK)^i($ICON_PATH/wifi.xbm)^fg() $wifi_name"
    else
        echo -n "Not Connected "
    fi
    return
}

function Date()
{
    date="$(date +"%d").$(date +"%b")"
    echo -n "^fg($PINK)^i($ICON_PATH/calendar.xbm)^fg() $date"
    return
}

function Time()
{
    hour=$(date +"%H:%M")
    echo -n "^fg($PINK)^i($ICON_PATH/clock.xbm)^fg() $hour"
    return
}

## Print Dzen2
##############
##############
while true                                                                                                                       
do
    echo "^pa(10)$(Kernel) $(Cpu) $(Root) $(Home) $(Ram) $(Swap) ^pa(615)$(Tag) ^pa(905)$(Temp) $(Battery) $(Brightness) $(Wifi) $(Date) $(Time)"
    sleep 1
done | dzen2 -ta l -fn $FONT -bg $BLACK2 -fg $GRAY -x $X -y $Y -w $WIDTH -h $HEIGHT
